FROM node:20-bullseye as build
WORKDIR /app
COPY package*.json .
RUN npm install
EXPOSE 8080
COPY ..  .
RUN npm run build

FROM nginx:alpine as prod
WORKDIR /usr/share/nginx/html
ENV VITE_RAWG_KEY=98987HJHJH87878KJ
EXPOSE 80
COPY --from=build /app/dist .