services:
  gamehub:
    image: node:22-bullseye-slim
    restart: unless-stopped
    command: sleep infinity
    ports:
      - 9090:8080
    env_file:
      - ../.env
    volumes:
      - ..:/workspaces/gamehub
