FROM node:20-alpine as build
WORKDIR /app
# USER node
COPY package*.json .
RUN npm install
EXPOSE 8080
COPY ..  .
EXPOSE 8080
ENV VITE_RAWG_KEY=98987HJHJH87878KJ
CMD [ "npm", "run", "dev" ]

# FROM nginx:alpine as prod
# WORKDIR /usr/share/nginx/html
# ENV VITE_RAWG_KEY=98987HJHJH87878KJ
# EXPOSE 80
# COPY --from=build /app/dist .